[tool.poetry]
name = "vae_anomaly_detection"
version = "1.0.0"
description = "Pytorch/TF1 implementation of Variational AutoEncoder for anomaly detection following the paper \"Variational Autoencoder based Anomaly Detection using Reconstruction Probability by Jinwon An, Sungzoon Cho\""
authors = ["mikedev <mik3dev@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8<3.10"
path = "^16.3.0"
torch = "1.10.1%2Bcpu"
pytorch-ignite = "^0.4.8"
PyYAML = ">=6.0"
tqdm = "^4.62.3"

[tool.poetry.dev-dependencies]
pytest = ">=7.0.1"

[[tool.poetry.source]]
name = "torch-repo"
url = "https://vxlabs.com/pypi/"  # relative path to local directory with wheel files
secondary = true


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
