
name: Python test and build

on:
  push:
    tags-ignore:
      - "*"
  schedule:
    - cron: "0 0 * * 0" # Run every Sunday at midnight
  workflow_dispatch: # Manually trigger a workflow run
    

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install hatch
        run: pip install hatch
      - name: Install dependencies
        run: pip install --extra-index-url https://download.pytorch.org/whl/cpu -r pyproject.toml .[dev]
      -  name: Test
         run: python -m pytest
      - name: Build
        run: hatch build